import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/flowbite-react/**/*.js',
  ],
  theme: {
    colors: {
      primary: {
        50: "#848586",
        100: "#484949",
        200: "#404041",
        300: "#262728",
        400: "#1b1c1e",
        500: "#191b1e",
        600: "#111725",
        700: "#060d23",
        800: "#040815",
        900: "#03050c",
      },
      secondary: {
        50: "#F1F2F2",
        100: "#F1F2F2",
        200: "#F1F2F2",
        300: "#F1F2F2",
        400: "#F1F2F2",
        500: "#F1F2F2",
        600: "#F1F2F2",
        700: "#F1F2F2",
        800: "#F1F2F2",
        900: "#F1F2F2",
      },
    },
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    extend: {},
  },
  plugins: [
      require('flowbite/plugin')
  ],
}
export default config
