import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import {getServerSession} from "next-auth";
import FlowbiteContext from "@/app/context/FlowbitContext";
import AuthProvider from "@/app/context/AuthProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const session = await getServerSession();
    const isLoggedIn = !!session;
    return (
        <html lang="en">
        <body>
        <FlowbiteContext>
            <AuthProvider>
                {isLoggedIn && (
                    <main>{children}</main>
                )}
                {!isLoggedIn && children}
            </AuthProvider>
        </FlowbiteContext>
        </body>
        {/*<body className={inter.className}>{children}</body>*/}
        </html>
    )
}
